export const CARD_CHARACTERS: Record<string, Record<string, { name: string; title?: string }>> = {
  spades: {
    'A': { name: 'Lord of the Mysteries', title: 'Apex Form' },
    'K': { name: 'Azik Eggers', title: 'Undying' },
    'Q': { name: 'Medici', title: 'Red Priest' },
    'J': { name: 'Will Auceptin', title: 'Angel of Fate' },
    '10': { name: 'Sharron', title: 'Prisoner' },
    '9': { name: 'Reinette Tinekerr', title: 'Chained' },
    '8': { name: 'Dark Angel Sasrir', title: 'Hanged Man' },
    '7': { name: 'Bernadette Gustav', title: 'Hermit' },
    '6': { name: 'Pallez Zoroast', title: 'Marauder' },
    '5': { name: 'Saint Arianna', title: 'Evernight' },
    '4': { name: 'Ancient Sun God', title: 'Creator' },
    '3': { name: 'Tyrant Demigod', title: 'Leodero' },
    '2': { name: 'Steam Demigod', title: 'Machinery' },
  },
  hearts: {
    'A': { name: 'Audrey Hall', title: 'Miss Justice' },
    'K': { name: 'Gehrman Sparrow', title: 'Mr. World' },
    'Q': { name: 'Xio Derecha', title: 'Miss Judgment' },
    'J': { name: 'Derrick Berg', title: 'Mr. Sun' },
    '10': { name: 'Fors Wall', title: 'Miss Magician' },
    '9': { name: 'Cattleya', title: 'Miss Hermit' },
    '8': { name: 'Leonard Mitchell', title: 'Mr. Star' },
    '7': { name: 'Emlyn White', title: 'Mr. Moon' },
    '6': { name: 'Alger Wilson', title: 'Mr. Hanged Man' },
    '5': { name: 'The Empress', title: 'Tarot Club' },
    '4': { name: 'The Emperor', title: 'Tarot Club' },
    '3': { name: 'The Hierophant', title: 'Tarot Club' },
    '2': { name: 'The Lovers', title: 'Tarot Club' },
  },
  diamonds: {
    'A': { name: 'Lord of the Mysteries', title: 'Omniscience' },
    'K': { name: 'Roselle Gustav', title: 'Black Emperor' },
    'Q': { name: 'Goddess of Wisdom', title: 'Knowledge' },
    'J': { name: 'Hvin Rambis', title: 'Spectator' },
    '10': { name: 'Ince Zangwill', title: 'Antagonist' },
    '9': { name: 'The Ancient Sage', title: 'God of Elves' },
    '8': { name: 'Paragon Demigod', title: 'Steam Church' },
    '7': { name: 'Hela', title: 'Nighthawk' },
    '6': { name: 'Secret Cult Head', title: 'Knowledge' },
    '5': { name: 'Spectator Demigod', title: 'Alchemists' },
    '4': { name: 'White Tower Demigod', title: 'Reader' },
    '3': { name: 'Marauder Parasite', title: 'Error' },
    '2': { name: 'Psychology Head', title: 'Spectator' },
  },
  clubs: {
    'A': { name: 'Lord of the Mysteries', title: 'Omnipotence' },
    'K': { name: 'God of Combat', title: 'Twilight Giant' },
    'Q': { name: 'Primordial Demoness', title: 'Disaster' },
    'J': { name: 'Aurora Order Head', title: 'Hanged Man' },
    '10': { name: 'The Cursed One', title: 'Prisoner' },
    '9': { name: 'Chimera of Fate', title: 'Monster' },
    '8': { name: 'Death Demigod', title: 'Undead' },
    '7': { name: 'Chained Demigod', title: 'Rose School' },
    '6': { name: 'Prisoner Demigod', title: 'Rose School' },
    '5': { name: 'Nature Demigod', title: 'Sylvan Lord' },
    '4': { name: 'Hanged Man Demigod', title: 'Secrets Suppliant' },
    '3': { name: 'Monster Demigod', title: 'Fate' },
    '2': { name: 'Transformation Being', title: 'Outsider' },
  }
};
